name: Deploy MERN App to Cloud Runner

on:
  push:
    branches:
      - main  # Runs the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use GitHub's cloud runner on Ubuntu

    services:
      mongodb:  # Set up a MongoDB service for testing (if required)
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust Node.js version as needed

      - name: Install Backend dependencies
        run: |
          npm install

      - name: Install Frontend dependencies
        run: |
          cd client
          npm install

      - name: Build Frontend
        run: |
          cd client  # Corrected from frontend to client
          npm run build

      - name: Test Backend
        run: |
          npm test  # Assumes test scripts are configured in root package.json

      - name: Set environment variables
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

      - name: Deploy Backend
        run: |
          npm start  # Ensure your start command is appropriate for production
